# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e2615588c2d6449b0672c749d5ea0dc9488c98e3567a1a6cde378ba5b74592c449ecfbea38f58c18c1e9826ef4acb053245be5f001d6dbc977f554ebce9622e0

test:
  secret_key_base: ac69a70cea52eba7fa8307524377a1da4556724aeb22071ba8cf58ca25b1efbf63b23be5dde4989a17adcc3146a1ae270394c1338f4acd8629a9905742835e59

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
